export interface IStaticMapShopsDW {
  dwDeathMtnShop
  dwDeathMtnFairy
  dwDesertFairy
  dwDesertHint
  dwPotionShop
  dwLakeHyliaFairy
  dwEastHint
  podHint
  dwForestShop
  dwLumberjackHutShop
  dwOutcastShop
  dwSanctuaryHint
  dwFortuneTeller
  dwLakeHyliaShop
  archeryGame
  dwBonkFairy
  dwLakeLedgeFairy
  dwLakeLedgeHint
  dwLakeLedgeSpikeCave
}
