export const defaultDungeons = {
    version: '0.0.2',
    data: {
        ep: {
            boss: false,
            crystal: 0,
            maxCrystal: 4,
            chests: 3,
            maxChests: 3,
            map: false,
            compass: false,
            bosskey: false,
            smallkeys: 0,
            maxSmallkeys: 2,
            medallion: 0,
            maxMedallion: 0
        }, // eastern palace
        dp: {
            boss: false,
            crystal: 0,
            maxCrystal: 4,
            chests: 2,
            maxChests: 2,
            map: false,
            compass: false,
            bosskey: false,
            smallkeys: 0,
            maxSmallkeys: 4,
            medallion: 0,
            maxMedallion: 0
        }, // desert palace
        toh: {
            boss: false,
            crystal: 0,
            maxCrystal: 4,
            chests: 2,
            maxChests: 2,
            map: false,
            compass: false,
            bosskey: false,
            smallkeys: 0,
            maxSmallkeys: 1,
            medallion: 0,
            maxMedallion: 0
        }, // tower of harrah
        aga: {
            boss: false,
            crystal: 0,
            maxCrystal: 0,
            chests: 0,
            maxChests: 0,
            map: false,
            compass: false,
            bosskey: false,
            smallkeys: 0,
            maxSmallkeys: 7,
            medallion: 0,
            maxMedallion: 0
        }, // aganhim
        pod: {
            boss: false,
            crystal: 0,
            maxCrystal: 4,
            chests: 5,
            maxChests: 5,
            map: false,
            compass: false,
            bosskey: false,
            smallkeys: 0,
            maxSmallkeys: 6,
            medallion: 0,
            maxMedallion: 0
        }, // palace of darkness
        sp: {
            boss: false,
            crystal: 0,
            maxCrystal: 4,
            chests: 6,
            maxChests: 6,
            map: false,
            compass: false,
            bosskey: false,
            smallkeys: 0,
            maxSmallkeys: 5,
            medallion: 0,
            maxMedallion: 0
        }, // swamp palace
        sw: {
            boss: false,
            crystal: 0,
            maxCrystal: 4,
            chests: 2,
            maxChests: 2,
            map: false,
            compass: false,
            bosskey: false,
            smallkeys: 0,
            maxSmallkeys: 5,
            medallion: 0,
            maxMedallion: 0
        }, // skull woods
        tt: {
            boss: false,
            crystal: 0,
            maxCrystal: 4,
            chests: 4,
            maxChests: 4,
            map: false,
            compass: false,
            bosskey: false,
            smallkeys: 0,
            maxSmallkeys: 3,
            medallion: 0,
            maxMedallion: 0
        }, // thieves town
        ip: {
            boss: false,
            crystal: 0,
            maxCrystal: 4,
            chests: 3,
            maxChests: 3,
            map: false,
            compass: false,
            bosskey: false,
            smallkeys: 0,
            maxSmallkeys: 6,
            medallion: 0,
            maxMedallion: 0
        }, // ice palace
        mm: {
            boss: false,
            crystal: 0,
            maxCrystal: 4,
            chests: 2,
            maxChests: 2,
            map: false,
            compass: false,
            bosskey: false,
            smallkeys: 0,
            maxSmallkeys: 6,
            medallion: 0,
            maxMedallion: 3
        }, // misery mire
        tr: {
            boss: false,
            crystal: 0,
            maxCrystal: 4,
            chests: 5,
            maxChests: 5,
            map: false,
            compass: false,
            bosskey: false,
            smallkeys: 0,
            maxSmallkeys: 6,
            medallion: 0,
            maxMedallion: 3
        }, // turtle rock
        gt: {
            boss: false,
            crystal: 0,
            maxCrystal: 0,
            chests: 20,
            maxChests: 20,
            map: false,
            compass: false,
            bosskey: false,
            smallkeys: 0,
            maxSmallkeys: 8,
            medallion: 0,
            maxMedallion: 0
        } // aganhim2
    }
}
