export const defaultMap = {
    version: '0.0.1',
    data: {
        lightworld: {
            mode:0, //0 for map, 1 for location list
            scale: 1,
            x: 0,
            y: 0,
            centerKey: undefined,
            locations: {
                uncle: {checked: false, klass:'locale-green'},
                secretPassage: {checked: false, klass:'locale-green'},
                backOfEscape: {checked: false, klass: 'locale-red'},
                sahashralaHut: {checked: false, klass:'locale-green'},
                sahashrala: {checked: false, klass:'locale-red'},
                potionShop:{checked: false, klass:'locale-red'},
                zora:{checked: false, klass:'locale-green'},
                zoraLedge:{checked: false, klass:'locale-red'},
                waterfallFairy:{checked: false, klass: 'locale-red'},
                pedestal:{checked: false, klass: 'locale-red'},
                kingTomb:{checked: false, klass: 'locale-red'},
                tavern:{checked: false, klass: 'locale-green'},
                chickenHut:{checked: false, klass: 'locale-red'},
                well:{checked: false, klass: 'locale-red'},
                blindhouse:{checked:false, klass: 'locale-red'},
                pegasusRock: {checked: false, klass: 'locale-red'},
                bottleMerchant: {checked: false, klass: 'locale-green'},
                magicBat: {checked: false, klass: 'locale-red'},
                sickKid: {checked: false, klass: 'locale-red'},
                lwHideout: {checked: false, klass: 'locale-green'},
                lumberjackTree: {checked: false, klass: 'locale-red'},
                graveyardLedge: {checked: false, klass: 'locale-red'},
                lwMushroom: {checked: false, klass: 'locale-green'},
                floodChest: {checked: false, klass: 'locale-green'},
                floodTreasure: {checked: false, klass: 'locale-green'},
                linkHouse: {checked: false, klass: 'locale-green'},
                aginahCave: {checked: false, klass: 'locale-red'},
                moldormCave: {checked: false, klass: 'locale-red'},
                iceRodCave: {checked: false, klass: 'locale-red'},
                hobo: {checked: false, klass: 'locale-red'},
                bombosTablet: {checked: false, klass: 'locale-red'},
                cave45: {checked: false, klass: 'locale-red'},
                checkerCave: {checked: false, klass: 'locale-red'},
                library: {checked: false, klass: 'locale-red'},
                mazeRace: {checked: false, klass: 'locale-red'},
                desertLedge: {checked: false, klass: 'locale-red'},
                lakeIsland: {checked: false, klass: 'locale-red'},
                fluteSpot: {checked: false, klass: 'locale-red'},
                oldMan: {checked: false, klass: 'locale-red'},
                spectacleRockCave: {checked: false, klass: 'locale-red'},
                etherTablet: {checked: false, klass: 'locale-red'},
                spectacleRock: {checked: false, klass: 'locale-red'},
                spiralCave: {checked: false, klass: 'locale-red'},
                mimicCave: {checked: false, klass: 'locale-red'},
                paradoxCave: {checked: false, klass: 'locale-red'},
                floatingIsland: {checked: false, klass: 'locale-red'},
            },
            dungeons: {
                ep:{klass:'locale-red'},
                dp:{klass: 'locale-red'},
                toh:{klass: 'locale-red'}
            },
            bosses: {
                ep:{klass:'locale-red'},
                dp:{klass: 'locale-red'},
                toh:{klass: 'locale-red'}
            }
        },
        darkworld: {}
    }
}
