export const staticMapDW = {
    superbunnyCave: {x: 1265, y: 223,title: 'Superbunny Cave', desc: '', req:[], validate(){return true;}},
    hookshotCave: {x: 1247, y: 99,title: 'Hookshot Cave', desc: '', req:[], validate(){return true;}},
    spikeCave: {x: 862, y: 221,title: 'Spike Cave', desc: '', req:[], validate(){return true;}},
    catfish: {x: 1341, y: 257,title: 'Catfish', desc: '', req:[], validate(){return true;}},
    pyramid: {x: 870, y: 670,title: 'Pyramid', desc: '', req:[], validate(){return true;}},
    pyramidFairy: {x: 703, y: 733,title: 'Pyramid Fairy', desc: '', req:[], validate(){return true;}},
    brewery: {x: 163, y: 878,title: 'Brewery', desc: '', req:[], validate(){return true;}},
    cShapeHouse: {x: 310, y: 726,title: 'C-Shaped House', desc: '', req:[], validate(){return true;}},
    chestGame: {x: 76, y: 702,title: 'Chest Game', desc: '', req:[], validate(){return true;}},
    hammerPegs: {x: 474, y: 908,title: 'Hammer Pegs', desc: '', req:[], validate(){return true;}},
    bumperCave: {x: 532, y: 268,title: '​Bumper Cave', desc: '', req:[], validate(){return true;}},
    blacksmith: {x: 223, y: 994,title: 'Blacksmith', desc: '', req:[], validate(){return true;}},
    purpleChest: {x: 457, y: 802,title: 'Purple Chest', desc: '', req:[], validate(){return true;}},
    hypeCave: {x: 1236, y: 972,title: 'Hype Cave', desc: '', req:[], validate(){return true;}},
    stumpy: {x: 463, y: 1024,title: 'Stumpy', desc: '', req:[], validate(){return true;}},
    diggingGame: {x: 85, y: 1043,title: 'Digging Game', desc: '', req:[], validate(){return true;}},
    mireShed: {x: 59, y: 1205,title: 'Mire Shed', desc: '', req:[], validate(){return true;}},
}
